<?php

/**
 * DO NOT edit this file under any circumstances. This file
 * calls the /lib/init.php file that sets up the entire framework.
 *
 * @package FrameShift
 * @since 1.0
 */
 
require_once( trailingslashit( get_template_directory() ) . 'lib/init.php' );

/**
 * WARNING! You can add your custom code snippets here. But keep in mind
 * that this file will be overwritten when you update the theme.
 * If you add code here, BACKUP this file before updating.
 */